sudo: reuired
services:
    - docker
before_install:
    - docker build -t anup210891/docker-react -f Dockerfile.dev .
script:
    - docker run anup210891/docker-react npm run test -- --coverage
deploy:
    provider: elaticbeanstalk
    region: "ap-south-1"
    app: "Docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-026787292270"
    bucket_path: "Docker-react"
    on: 
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
    
